# Generated by Django 2.2.15 on 2020-08-27 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='site_wide',
            new_name='enabled',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='enabled'),
        ),
    ]
