# Generated by Django 2.2.15 on 2020-08-27 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_auto_20200827_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['dismissal_type', '-publish_start'], 'verbose_name': 'announcement', 'verbose_name_plural': 'announcements'},
        ),
        migrations.AddField(
            model_name='announcement',
            name='announcement_style',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='announcement style'),
        ),
    ]
