# Generated by Django 2.2.15 on 2020-08-27 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_auto_20200827_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-enabled', '-publish_start'], 'verbose_name': 'announcement', 'verbose_name_plural': 'announcements'},
        ),
    ]
