# Generated by Django 2.2.15 on 2020-08-27 04:33

from django.db import migrations
import fontawesome.fields


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_auto_20200827_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='icon',
            field=fontawesome.fields.IconField(blank=True, max_length=60, verbose_name='fontawesome icon'),
        ),
    ]
