# Generated by Django 2.2.15 on 2020-08-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0006_auto_20200827_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['order', '-enabled'], 'verbose_name': 'announcement', 'verbose_name_plural': 'announcements'},
        ),
        migrations.AddField(
            model_name='announcement',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
