# Generated by Django 2.2.15 on 2020-09-02 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0007_auto_20200827_1929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['order'], 'verbose_name': 'announcement', 'verbose_name_plural': 'announcements'},
        ),
    ]
